### PR TITLE
Add db write option

### PR DESCRIPTION
**Pull request by mauriciofreshw**

### CODE REVIEW

**Comment by ashtonmeuser** [comment]
@mauriciofreshw Should we apply the same condition to the `sendPhacToSBC` job?

**Comment by mauriciofreshw** [comment]
> @mauriciofreshw Should we apply the same condition to the `sendPhacToSBC` job?

We have conditions on **mark-duplicates.js** used by `sendPhacToSBC`, we still want Infos about what the lambda would do, so the job is not entirely off.

**Review by fwkendall — APPROVED** [review]
Looks great 👍

**Comment by fwkendall** [comment]
> > @mauriciofreshw Should we apply the same condition to the `sendPhacToSBC` job?
> 
> We have conditions on **mark-duplicates.js** used by `sendPhacToSBC`, we still want Infos about what the lambda would do, so the job is not entirely off.

I think it wouldn't hurt to add it to sendPhacToSBC as well, as in the function in send-to-sbc.js. That's more of a failsafe than anything since the changes in mark-duplicates.js *should* prevent that from being called.

**Comment by mauriciofreshw** [comment]
> > > @mauriciofreshw Should we apply the same condition to the `sendPhacToSBC` job?
> > 
> > 
> > We have conditions on **mark-duplicates.js** used by `sendPhacToSBC`, we still want Infos about what the lambda would do, so the job is not entirely off.
> 
> I think it wouldn't hurt to add it to sendPhacToSBC as well, as in the function in send-to-sbc.js. That's more of a failsafe than anything since the changes in mark-duplicates.js _should_ prevent that from being called.

Totally, just added. Thanks :)

**Review by ashtonmeuser — APPROVED** [review]

**Pull request merged**
